datasets:
  name: recipe_dataset
  root_dir: data/archive
  recipes_path: ${datasets.root_dir}/PP_recipes.csv
  ingr_map_path: ${datasets.root_dir}/ingr_map.pkl

model:
  d_model: 128
  nhead: 8
  num_layers: 4
  dropout: 0.1
  activation: relu

optimizer:
  beta: 0.01
  lr: 0.1
  type: adam
  grad_clip: False

compute:
  hardware: cpu
  precision: 32
  num_workers: 1

train:
  batch_size: 128
  train_frac: 0.7
  val_frac: 0.2
  test_frac: 0.1

steps:
  log_every: 10
  val_every: 100

file:
  log: False
  save_path: False
  load_path: False
  run_name: False
