datasets:
  name: recipe_dataset
  recipes_path: data/archive/PP_recipes.csv
  ingr_map_path: data/archive/ingr_map.pkl
data_augmentation:
  batch_size: 10
  train_frac: 0.7
  val_frac: 0.2
  test_frac: 0.1
architecture:
  d_model: 128
  n_heads: 8
optimizer:
  beta: 0.01
  lr: 0.1
  type: adam
compute:
  hardware: cpu
  precision: 32
file:
  save_path: None
  load_path: None
