datasets:
  name: recipe_dataset
  root_dir: data/archive
  recipes_path: ${datasets.root_dir}/PP_recipes.csv
  ingr_map_path: ${datasets.root_dir}/ingr_map.pkl

masking:
  frac_augmented: 0.15 # fraction of tokens to mask
  frac_masked: 0.8 # fraction of augmented tokens to set to MASK
  frac_random: 0.1 # fraction of augmented tokens to set to random token
  frac_unchanged: 0.1 # fraction of augmented tokens to keep the same

model:
  d_model: 128 # dimensionality of model features
  nhead: 8 # number of attentions heads per layer
  num_layers: 4 # number of self-attention layers in transformer
  dropout: 0.1 # dropout fraction in FFN at each layer
  activation: relu # activation in FFN at each layer

optimizer:
  # beta: 0.01
  lr: 0.1 # learning rate of optimizer
  type: adam # type of optimizer
  grad_clip: False # gradient clipping

compute:
  hardware: cpu
  precision: 32
  num_workers: 1

train:
  batch_size: 128
  train_frac: 0.7
  val_frac: 0.2
  test_frac: 0.1

steps:
  log_every: 10
  val_every: 100

file:
  log: False
  save_path: False
  load_path: False
  run_name: False
